name: todo_app_provider
description: This is Todo App in Provider

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  lottie: ^2.4.0

  # for url
  url_launcher: ^6.1.11

  # device path
  permission_handler: ^10.3.0

  # hive database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # network
  dio: ^5.3.0

  # network connection
  connectivity_plus: ^4.0.1

  # dependency injection
  get_it: ^7.6.0

  # state management
  provider: ^6.0.5

  # annotation
  freezed_annotation: ^2.4.1
  flutter_slidable: ^3.0.0
  sqflite: ^2.2.8+4
  path: ^1.8.3
  flutter_secure_storage: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # linter
  flutter_lints: ^2.0.0

  # hive generate
  hive_generator: ^2.0.0

  # dart generator
  build_runner: ^2.4.5

  # json parsing
  json_serializable: ^6.7.0
  freezed: ^2.3.5


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700